# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Command
Command.create!(name: 'Reoprimatev', region: 'Austria')
Command.create!(name: 'Mijoroayf', region: 'Belgium')
Command.create!(name: 'Bsktballpimpwy', region: 'Bulgaria')
Command.create!(name: 'Oiseaublancuw', region: 'Denmark')
Command.create!(name: 'Corbelrt', region: 'Finland')
Command.create!(name: 'Urinprobetn', region: 'France')
Command.create!(name: 'Duane774lb', region: 'Germany')
Command.create!(name: 'Hauhacamyxc', region: 'Greece')
Command.create!(name: 'Ht10224aq', region: 'Hungary')
Command.create!(name: 'Acomanarsak', region: 'Ireland')
Command.create!(name: 'Adlamauni', region: 'Spain')
Command.create!(name: 'Seijuudj', region: 'Poland')
Command.create!(name: 'Mantakh', region: 'United Kingdom')

#User
 User.create!(name: 'ibanez9019h8', phone:  '7804516', male:  'm', command_id:  '1')
 User.create!(name: 'tympboyyk', phone:  '1006717', male:  'm', command_id:  '1')
 User.create!(name: 'Walzradaz', phone:  '7939994', male:  'm', command_id:  '1')
 User.create!(name: 'abrandeseh', phone:  '5487056', male:  'w', command_id:  '1')
 User.create!(name: 'muradyann0', phone:  '7041031', male:  'w', command_id:  '1')
 User.create!(name: 'YBHL1YAbe', phone:  '1320912', male:  'w', command_id:  '2')
 User.create!(name: 'brandnewstarts4', phone:  '1166503', male:  'm', command_id:  '2')
 User.create!(name: 'dolskanp', phone:  '8737320', male:  'w', command_id:  '2')
 User.create!(name: 'cdetorewu', phone:  '3382404', male:  'w', command_id:  '2')
 User.create!(name: 'jaiyikendrad5', phone:  '5554660', male:  'm', command_id:  '1')
 User.create!(name: 'trosnodc1', phone:  '9319181', male:  'm', command_id:  '1')
 User.create!(name: 'dadcotp', phone:  '3835062', male:  'm', command_id:  '2')
 User.create!(name: 'problemuja', phone:  '1629174', male:  'm', command_id:  '3')
 User.create!(name: 'samu19850j', phone:  '9439360', male:  'w', command_id:  '3')
 User.create!(name: 'slonovaxl', phone:  '7237519', male:  'w', command_id:  '3')
 User.create!(name: 'guggath', phone:  '5134296', male:  'm', command_id:  '3')
 User.create!(name: 'huchomozazi', phone:  '3435267', male:  'w', command_id:  '4')
 User.create!(name: 'Hatalukuvk', phone:  '2007620', male:  'm', command_id:  '4')
 User.create!(name: 'Andromarixv', phone:  '1251663', male:  'w', command_id:  '4')
 User.create!(name: 'stinky91101em', phone:  '2480712', male:  'm', command_id:  '4')
 User.create!(name: 'sostae3', phone:  '8737926', male:  'w', command_id:  '4')
 User.create!(name: 'helitydd87', phone:  '7503617', male:  'w', command_id:  '4')
 User.create!(name: 'Paruzain', phone:  '3950098', male:  'm', command_id:  '5')
 User.create!(name: 'rosedunjourr9', phone:  '9161933', male:  'w', command_id:  '5')
 User.create!(name: 'borbaigh3a', phone:  '5162802', male:  'w', command_id:  '5')
 User.create!(name: 'michigani7v', phone:  '3719904', male:  'm', command_id:  '5')
 User.create!(name: 'sdes2zjw', phone:  '3789594', male:  'm', command_id:  '5')
 User.create!(name: 'Buiglan', phone:  '6836242', male:  'm', command_id:  '5')
 User.create!(name: 'Issuefattsh', phone:  '2507877', male:  'm', command_id:  '5')
 User.create!(name: 'blacklavelef', phone:  '7155413', male:  'm', command_id:  '5')
 User.create!(name: 'doppemeulnh', phone:  '2509172', male:  'm', command_id:  '5')
 User.create!(name: 'Colauttipa', phone:  '5826976', male:  'w', command_id:  '6')
 User.create!(name: 'Scediakekuh', phone:  '2217811', male:  'w', command_id:  '6')
 User.create!(name: 'Wrabeurodadesy9', phone:  '2656706', male:  'w', command_id:  '6')
 User.create!(name: 'zbujenegax8', phone:  '3771243', male:  'm', command_id:  '6')
 User.create!(name: 'vuurstaalkc', phone:  '9273494', male:  'w', command_id:  '6')
 User.create!(name: 'twetaencumn4b', phone:  '4198243', male:  'w', command_id:  '6')
 User.create!(name: 'mollstemt6w', phone:  '2372539', male:  'm', command_id:  '6')
 User.create!(name: 'teiscegu', phone:  '2824641', male:  'm', command_id:  '7')
 User.create!(name: 'fyddont04', phone:  '276575', male:  'm', command_id:  '7')
 User.create!(name: 'desjacis9s', phone:  '9569795', male:  'm', command_id:  '7')
 User.create!(name: 'dormesli', phone:  '8793964', male:  'w', command_id:  '7')
 User.create!(name: 'adozenrozess2', phone:  '7304311', male:  'w', command_id:  '7')
 User.create!(name: 'Barzanav7', phone:  '7286031', male:  'm', command_id:  '7')
 User.create!(name: 'damunterx2', phone:  '482141', male:  'w', command_id:  '8')
 User.create!(name: 'makacheroti', phone:  '6757486', male:  'm', command_id:  '8')
 User.create!(name: 'peglezt4', phone:  '6782400', male:  'w', command_id:  '8')
 User.create!(name: 'istragev6', phone:  '2081919', male:  'm', command_id:  '8')
 User.create!(name: 'minderlypq', phone:  '3145719', male:  'w', command_id:  '8')
 User.create!(name: 'Woncorymmeddyb3', phone:  '6815382', male:  'w', command_id:  '8')
 User.create!(name: 'Zandonadi5d', phone:  '2401508', male:  'm', command_id:  '8')
 User.create!(name: 'trpeowy', phone:  '9400714', male:  'w', command_id:  '9')
 User.create!(name: 'Hinternahi1', phone:  '4998568', male:  'w', command_id:  '9')
 User.create!(name: 'Korselettyk', phone:  '5135365', male:  'm', command_id:  '9')
 User.create!(name: 'jennxisxrads9', phone:  '5163902', male:  'm', command_id:  '9')
 User.create!(name: 'FiepsyFerpent19', phone:  '2378657', male:  'm', command_id:  '9')
 User.create!(name: 'onenonlyzen64', phone:  '2181593', male:  'm', command_id:  '9')
 User.create!(name: 'sflays13oq', phone:  '9549945', male:  'm', command_id:  '9')
 User.create!(name: 'penwynner1c', phone:  '5321547', male:  'm', command_id:  '10')
 User.create!(name: 'Nordkapiv', phone:  '2931039', male:  'w', command_id:  '10')
 User.create!(name: 'lance200631', phone:  '8379112', male:  'w', command_id:  '10')
 User.create!(name: 'starfish2b', phone:  '5408929', male:  'w', command_id:  '10')
 User.create!(name: 'stomacso', phone:  '2581764', male:  'm', command_id:  '10')
 User.create!(name: 'dilafilali', phone:  '6553279', male:  'w', command_id:  '10')
 User.create!(name: 'hunau8u', phone:  '278717', male:  'w', command_id:  '10')
 User.create!(name: 'Prekdeecypeoo', phone:  '9285432', male:  'm', command_id:  '10')
 User.create!(name: 'Galatiana2b', phone:  '8853398', male:  'm', command_id:  '10')
 User.create!(name: 'Tauchereiuq', phone:  '5512429', male:  'm', command_id:  '10')
 User.create!(name: 'atapits0s ', phone:  '819736', male:  'm', command_id:  '10')
 User.create!(name: 'aeqybzkmvh9', phone:  '8306081', male:  'w', command_id:  '10')
 User.create!(name: 'bambino1998gy', phone:  '60500', male:  'w', command_id:  '11')
 User.create!(name: 'nikooru89ns', phone:  '2649520', male:  'm', command_id:  '11')
 User.create!(name: 'Ardinopc', phone:  '2988608', male:  'w', command_id:  '11')
 User.create!(name: 'Gelletti2g', phone:  '5225120', male:  'm', command_id:  '11')
 User.create!(name: 'Kubhahela10', phone:  '9132285', male:  'w', command_id:  '11')
 User.create!(name: 'l8nightcattyvg', phone:  '6054231', male:  'm', command_id:  '11')
 User.create!(name: 'hipurowy6h', phone:  '1700112', male:  'w', command_id:  '11')
 User.create!(name: 'lilikutaap', phone:  '3529421', male:  'w', command_id:  '11')
 User.create!(name: 'solmartingr', phone:  '9040635', male:  'm', command_id:  '11')
 User.create!(name: 'ovenpaalev', phone:  '7035095', male:  'w', command_id:  '11')
 User.create!(name: 'xxurbanerdxxb7', phone:  '6147499', male:  'w', command_id:  '11')
 User.create!(name: 'carduzo1g', phone:  '1474277', male:  'm', command_id:  '11')
 User.create!(name: 'rgomezgalindoua', phone:  '9613306', male:  'm', command_id:  '12')
 User.create!(name: 'asincronosja', phone:  '4193707', male:  'm', command_id:  '12')
 User.create!(name: 'situirali2e', phone:  '6267294', male:  'm', command_id:  '12')
 User.create!(name: 'Juzais', phone:  '121072', male:  'm', command_id:  '12')
 User.create!(name: 'mulcta1o', phone:  '1761170', male:  'm', command_id:  '12')
 User.create!(name: 'vagappevea7', phone:  '9163678', male:  'w', command_id:  '12')
 User.create!(name: 'poblem7r', phone:  '7637538', male:  'w', command_id:  '12')
 User.create!(name: 'Prendonizo', phone:  '5744810', male:  'w', command_id:  '12')
 User.create!(name: 'Coubsweessye3', phone:  '6759665', male:  'm', command_id:  '12')
 User.create!(name: 'Stitteekemoa2', phone:  '2630382', male:  'w', command_id:  '12')
 User.create!(name: 'botkanker9g', phone:  '5777130', male:  'w', command_id:  '12')
 User.create!(name: 'ddaethan', phone:  '1482057', male:  'm', command_id:  '12')
 User.create!(name: 'OmiseeDew66', phone:  '2283345', male:  'm', command_id:  '13')
 User.create!(name: 'bloguotin4q', phone:  '2453810', male:  'm', command_id:  '13')
 User.create!(name: 'analemalk', phone:  '2462490', male:  'm', command_id:  '13')
 User.create!(name: 'adlemaisbx', phone:  '4364582', male:  'w', command_id:  '13')
 User.create!(name: 'aprimeishiu', phone:  '5131265', male:  'w', command_id:  '13')
 User.create!(name: 'sebaceegv', phone:  '5476602', male:  'm', command_id:  '13')
 
 
