
#People
# User.create!(name: '4meArticle', password: '12345', type: 'Friend')
# User.create!(name: 'Adfoscot', password: '12345', type: 'Friend')
# User.create!(name: 'Aimal', password: '12345', type: 'Friend')
# User.create!(name: 'Alertra', password: '12345', type: 'Friend')
# User.create!(name: 'Arane', password: '12345', type: 'Friend')
# User.create!(name: 'Asparket', password: '12345', type: 'Friend')
# User.create!(name: 'Bancturer', password: '12345', type: 'Friend')
# User.create!(name: 'Bigosco', password: '12345', type: 'Friend')
# User.create!(name: 'Blikingsk', password: '12345', type: 'Friend')
# User.create!(name: 'Booker', password: '12345', type: 'Friend')
# User.create!(name: 'Borniary', password: '12345', type: 'Friend')
# User.create!(name: 'BoyHeadline', password: '12345', type: 'Friend')
# User.create!(name: 'Brightra', password: '12345', type: 'Friend')
# User.create!(name: 'BugBook', password: '12345', type: 'Friend')
# User.create!(name: 'Capteril', password: '12345', type: 'Friend')
# User.create!(name: 'Celtech', password: '12345', type: 'Friend')
# User.create!(name: 'Cheerubb', password: '12345', type: 'Friend')
# User.create!(name: 'Cheeruxt', password: '12345', type: 'Friend')
# User.create!(name: 'Choosentco', password: '12345', type: 'Friend')
# User.create!(name: 'Columneton', password: '12345', type: 'Friend')
# User.create!(name: 'Combilc', password: '12345', type: 'Friend')
# User.create!(name: 'Confideprov', password: '12345', type: 'Friend')
# User.create!(name: 'CuddlySparkling', password: '12345', type: 'Friend')
# User.create!(name: 'Debolisa', password: '12345', type: 'Friend')
# User.create!(name: 'Dreamyde', password: '12345', type: 'Friend')
# User.create!(name: 'EdgyVital', password: '12345', type: 'Friend')
# User.create!(name: 'Essenli', password: '12345', type: 'Friend')
# User.create!(name: 'Exarisata', password: '12345', type: 'Friend')
# User.create!(name: 'Fairerkl', password: '12345', type: 'Friend')
# User.create!(name: 'Fencuphr', password: '12345', type: 'Friend')
User.create!(name: 'Firstombs', password: '12345', type: 'Enemy')
User.create!(name: 'ForumHeadlines', password: '12345', type: 'Enemy')
User.create!(name: 'Fresherpt', password: '12345', type: 'Enemy')
User.create!(name: 'Frogixir', password: '12345', type: 'Enemy')
User.create!(name: 'GatoCookie', password: '12345', type: 'Enemy')
User.create!(name: 'Genbrogo', password: '12345', type: 'Enemy')
User.create!(name: 'Ginolo', password: '12345', type: 'Enemy')
User.create!(name: 'Glebanken', password: '12345', type: 'Enemy')
User.create!(name: 'Greyetto', password: '12345', type: 'Enemy')
User.create!(name: 'GriffonLovely', password: '12345', type: 'Enemy')
User.create!(name: 'Homewit', password: '12345', type: 'Enemy')
User.create!(name: 'HulkComment', password: '12345', type: 'Enemy')
User.create!(name: 'Hymnavite', password: '12345', type: 'Enemy')
User.create!(name: 'Hypeakeo', password: '12345', type: 'Enemy')
User.create!(name: 'IamaKlug', password: '12345', type: 'Enemy')
User.create!(name: 'Inovari', password: '12345', type: 'Enemy')
User.create!(name: 'Juringas', password: '12345', type: 'Enemy')
User.create!(name: 'KatrPark', password: '12345', type: 'Enemy')
User.create!(name: 'Ketcharra', password: '12345', type: 'Enemy')
User.create!(name: 'Lawniath', password: '12345', type: 'Enemy')
User.create!(name: 'Leketsgi', password: '12345', type: 'Enemy')
User.create!(name: 'Lencinar', password: '12345', type: 'Enemy')
User.create!(name: 'Leonie', password: '12345', type: 'Enemy')
User.create!(name: 'Lickfish', password: '12345', type: 'Enemy')
User.create!(name: 'Logenot', password: '12345', type: 'Enemy')
User.create!(name: 'LordDr', password: '12345', type: 'Enemy')
User.create!(name: 'Lysearna', password: '12345', type: 'Enemy')
User.create!(name: 'Maddlege', password: '12345', type: 'Enemy')
User.create!(name: 'ManHyper', password: '12345', type: 'Enemy')
User.create!(name: 'Megsys', password: '12345', type: 'Enemy')
User.create!(name: 'Metrouppl', password: '12345', type: 'Neutrality')
User.create!(name: 'Meydeldsh', password: '12345', type: 'Neutrality')
User.create!(name: 'MotoBlink', password: '12345', type: 'Neutrality')
User.create!(name: 'NanStud', password: '12345', type: 'Neutrality')
User.create!(name: 'Newsmi', password: '12345', type: 'Neutrality')
User.create!(name: 'Paxfinics', password: '12345', type: 'Neutrality')
User.create!(name: 'Primerci', password: '12345', type: 'Neutrality')
User.create!(name: 'PuppyChunky', password: '12345', type: 'Neutrality')
User.create!(name: 'Purdions', password: '12345', type: 'Neutrality')
User.create!(name: 'Rappath', password: '12345', type: 'Neutrality')
User.create!(name: 'Readynavi', password: '12345', type: 'Neutrality')
User.create!(name: 'SaviorPuff', password: '12345', type: 'Neutrality')
User.create!(name: 'ScreeDigest', password: '12345', type: 'Neutrality')
User.create!(name: 'Seabrig', password: '12345', type: 'Neutrality')
User.create!(name: 'Shamissu', password: '12345', type: 'Neutrality')
User.create!(name: 'Shinymyso', password: '12345', type: 'Neutrality')
User.create!(name: 'ShoppingBob', password: '12345', type: 'Neutrality')
User.create!(name: 'Shortlane', password: '12345', type: 'Neutrality')
User.create!(name: 'SincereMister', password: '12345', type: 'Neutrality')
User.create!(name: 'SlyGazette', password: '12345', type: 'Neutrality')
User.create!(name: 'SoundAway', password: '12345', type: 'Neutrality')
User.create!(name: 'SpoiledHeart', password: '12345', type: 'Neutrality')
User.create!(name: 'Statuste', password: '12345', type: 'Neutrality')
User.create!(name: 'StripperDream', password: '12345', type: 'Neutrality')
User.create!(name: 'Sudoris', password: '12345', type: 'Neutrality')
User.create!(name: 'Summeca', password: '12345', type: 'Neutrality')
User.create!(name: 'Sunnyance', password: '12345', type: 'Neutrality')
User.create!(name: 'Superca', password: '12345', type: 'Neutrality')
User.create!(name: 'Taructiv', password: '12345', type: 'Neutrality')
User.create!(name: 'Thinkie', password: '12345', type: 'Neutrality')
User.create!(name: 'Toolscart', password: '12345', type: 'Neutrality')
User.create!(name: 'Toxionds', password: '12345', type: 'Neutrality')
User.create!(name: 'Trevorks', password: '12345', type: 'Neutrality')
User.create!(name: 'Troikon', password: '12345', type: 'Neutrality')
User.create!(name: 'Tudentca', password: '12345', type: 'Neutrality')
User.create!(name: 'Uouterfa', password: '12345', type: 'Neutrality')
User.create!(name: 'Vestenyip', password: '12345', type: 'Neutrality')
User.create!(name: 'Vittalmax', password: '12345', type: 'Neutrality')
User.create!(name: 'WaterLyfe', password: '12345', type: 'Neutrality')
User.create!(name: 'Wickedle', password: '12345', type: 'Neutrality')
